### ISSUE TITLE
Document theming

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xtermjs.org#10]
I got a question on Gitter about how to set the theme, @scragg0x then built a [nice Sass helper](https://gist.github.com/scragg0x/c528da983443c4eecd59d8563b2c1507) to generate the colors, we should document how to do it on the site.

**Comment by LucaT1** [comment]
I think this is outdated nowadays, after the v3 update, and can be closed.

**Comment by Tyriar** [comment]
It is indeed 😄
