### ISSUE TITLE
Improve documentation for website

### ISSUE THREAD

**Issue by Mia-Y-Kelly** [xtermjs/xtermjs.org#202]
I'd like to update the docs so that the descriptions of the functions are included on the README's. The links to the actual code are nice, but it would be more intuitive to have them also included on the website.

**Comment by Tyriar** [comment]
Not sure what you mean by adding the function descriptions to the readmes?

**Comment by Mia-Y-Kelly** [comment]
I may be incorrect, but it looks like the website pulls from Markdown files like [`this`](https://github.com/xtermjs/xtermjs.org/blob/master/_docs/api/terminal/classes/terminal.md) (for example) to show documentation. I would like to update them to include more verbose descriptions.

**Comment by Tyriar** [comment]
Those files are auto-generated from the source (mostly xterm.d.ts)

**Comment by Tyriar** [comment]
Contributions to improve the api docs are welcome at https://github.com/xtermjs/xterm.js/blob/master/typings/xterm.d.ts and https://github.com/xtermjs/xterm.js/blob/master/typings/xterm-headless.d.ts
