### ISSUE TITLE
Add Hyper to Real-world uses in the webpage

### ISSUE THREAD

**Issue by blazeu** [xtermjs/xtermjs.org#41]
[Hyper](https://github.com/zeit/hyper) is terminal built with web technologies.

Since version 2 it's using xterm.js, https://zeit.co/blog/hyper2

**Comment by Tyriar** [comment]
Sure we could add Hyper to the list on the webpage as it's one of the biggest consumers now. I know it's already on the primary list on the xterm.js repo readme: https://github.com/xtermjs/xterm.js/blob/master/README.md#real-world-uses

**Comment by blazeu** [comment]
Ah I didn't see that repo first, went straight to this repo after seeing the webpage from zeit's blog.

Maybe we could add another big consumer to the webpage as well..
