### ISSUE TITLE
Give an example of loading xtermjs from a cdn in the docs example

### ISSUE THREAD

**Issue by epicfaace** [xtermjs/xtermjs.org#60]
This would make it easier for people to get started.

**Comment by Tyriar** [comment]
Isn't it just a matter of switching out these local files for CDN ones?

```
      <link rel="stylesheet" href="node_modules/xterm/dist/xterm.css" />
      <script src="node_modules/xterm/dist/xterm.js"></script>
```

I don't think we want to encourage the use of CDNs for this as they may lag behind npm and it adds an extra round trip to the CDN.

**Comment by jerch** [comment]
CDN usage should be discouraged for security reasons as well, unless you can ensure its data integrity by an secured upload and later fetch (chain of trust).

@Tyriar Imho this can be closed as wont fix.

**Comment by epicfaace** [comment]
Makes sense -- thanks for the explanations, @Tyriar and @jerch !

**Comment by rfl890** [comment]
Sorry for necroposting, but just wanted to revisit this issue. CDN's are pretty much the standard for loading libraries now, and [jsDelivr](https://jsdelivr.com) is a very popular npm cdn (like unpkg) that's quite fast and supports SRI. So a simple swap out to `<script src="https://cdn.jsdelivr.net/npm/xterm@5.0.0/lib/xterm.js" integrity="sha384-/XCg80+L4V8GHwr3ghm7ukvciSG3P/9AA5FnCAPS2SDmmaaxAkhuzh5SW/BuPFdo" crossorigin="anonymous"></script>` etc would be more efficient and beginner friendly (as you can just paste and go) than hosting files on your local server. Keep in mind this is just my opinion, but I would recommend considering it.
